"""Lasm: deterministic Sans I/O modeling and conformance evaluation of operational meaning.

Domain functions accept materialized values and return materialized values. They do not
read files, call networks, access databases or environment variables, start processes,
consult clocks, run agents, or connect to MCP servers. Reference fixtures live separately
in ``lasm_core.fixtures`` and are not imported here.
"""

from .conformance import ConformanceCase
from .domain import (
    EvidencePayload,
    JsonPrimitive,
    JsonValue,
    ValidationFinding,
    ValidationResult,
    ValidationSeverity,
    validation_result,
)
from .evaluate import (
    ConformanceEvaluation,
    DimensionResult,
    DivergenceSource,
    EvaluationDimension,
    EvaluationFinding,
    EvaluationFindingSeverity,
    EvaluationStatus,
    evaluate_conformance,
)
from .harness import (
    ApprovalFlow,
    ContextSensitivity,
    ContextSurface,
    HandoffBoundary,
    HarnessDescriptor,
    InteractionMode,
    PermissionLevel,
    PermissionModel,
)
from .interchange import (
    DOCUMENT_KINDS,
    SUPPORTED_SCHEMA_VERSIONS,
    DocumentDecodeResult,
    DocumentEncodeResult,
    DocumentKind,
    decode_document,
    encode_document,
    validate_document,
    wrap_document,
)
from .lasm import (
    ConceptEntry,
    ConstraintEntry,
    EventEntry,
    LasmEntryBase,
    LasmProjectionReferences,
    LogicalAssemblyEntry,
    LogicalAssemblySlice,
    PolicyEntry,
    ProvenanceKind,
    ProvenanceSource,
    ProvenanceStatus,
    RelationEntry,
    RuntimeEvaluationDescriptor,
    RuntimeEvaluationMode,
    logical_assembly_entries,
    logical_assembly_entry_ids,
)
from .mcp import McpPrimitiveDescriptor, McpRisk, McpSurfaceDescriptor, mcp_primitives
from .operational_state import (
    ActorObservation,
    OperationalState,
    OperationalStateField,
    OutcomeDisposition,
    OutcomeExpectation,
    StateTransitionExpectation,
    TransitionDisposition,
)
from .scenario import (
    AutomotiveDomain,
    BusinessContext,
    EvaluationExpectations,
    ExpectedControlSurfaces,
    RealityReferenceSet,
    Scenario,
    UserIntent,
)
from .skill import SkillDescriptor, SkillReference, SkillReferenceKind
from .trace import (
    AGENTIC_EVENT_TYPES,
    AgenticEventType,
    NormalizedTraceEvent,
    RawTraceEvent,
    TraceNormalizationResult,
    is_agentic_event_type,
    normalize_trace,
    trace_evidence_ref,
)
from .validate import (
    validate_actor_observation,
    validate_conformance_case,
    validate_harness,
    validate_logical_assembly,
    validate_mcp_surface,
    validate_operational_state,
    validate_outcome,
    validate_scenario,
    validate_skill,
    validate_state_transition,
    validate_trace,
)

__version__ = "0.2.0"

__all__ = [
    "AGENTIC_EVENT_TYPES",
    "DOCUMENT_KINDS",
    "SUPPORTED_SCHEMA_VERSIONS",
    "ActorObservation",
    "AgenticEventType",
    "ApprovalFlow",
    "AutomotiveDomain",
    "BusinessContext",
    "ConceptEntry",
    "ConformanceCase",
    "ConformanceEvaluation",
    "ConstraintEntry",
    "ContextSensitivity",
    "ContextSurface",
    "DimensionResult",
    "DivergenceSource",
    "DocumentDecodeResult",
    "DocumentEncodeResult",
    "DocumentKind",
    "EvaluationDimension",
    "EvaluationExpectations",
    "EvaluationFinding",
    "EvaluationFindingSeverity",
    "EvaluationStatus",
    "EventEntry",
    "EvidencePayload",
    "ExpectedControlSurfaces",
    "HandoffBoundary",
    "HarnessDescriptor",
    "InteractionMode",
    "JsonPrimitive",
    "JsonValue",
    "LasmEntryBase",
    "LasmProjectionReferences",
    "LogicalAssemblyEntry",
    "LogicalAssemblySlice",
    "McpPrimitiveDescriptor",
    "McpRisk",
    "McpSurfaceDescriptor",
    "NormalizedTraceEvent",
    "OperationalState",
    "OperationalStateField",
    "OutcomeDisposition",
    "OutcomeExpectation",
    "PermissionLevel",
    "PermissionModel",
    "PolicyEntry",
    "ProvenanceKind",
    "ProvenanceSource",
    "ProvenanceStatus",
    "RawTraceEvent",
    "RealityReferenceSet",
    "RelationEntry",
    "RuntimeEvaluationDescriptor",
    "RuntimeEvaluationMode",
    "Scenario",
    "SkillDescriptor",
    "SkillReference",
    "SkillReferenceKind",
    "StateTransitionExpectation",
    "TraceNormalizationResult",
    "TransitionDisposition",
    "UserIntent",
    "ValidationFinding",
    "ValidationResult",
    "ValidationSeverity",
    "decode_document",
    "encode_document",
    "evaluate_conformance",
    "is_agentic_event_type",
    "logical_assembly_entries",
    "logical_assembly_entry_ids",
    "mcp_primitives",
    "normalize_trace",
    "trace_evidence_ref",
    "validate_actor_observation",
    "validate_conformance_case",
    "validate_document",
    "validate_harness",
    "validate_logical_assembly",
    "validate_mcp_surface",
    "validate_operational_state",
    "validate_outcome",
    "validate_scenario",
    "validate_skill",
    "validate_state_transition",
    "validate_trace",
    "validation_result",
    "wrap_document",
]
